### ISSUE TITLE
Question and Request

### ISSUE THREAD

**Issue by mupsje** [vaproloff/universalThermostat#12]
I would like to express my gratitude for the development of this thermostat—it's simply "great." I've been searching for a thermostat that I can operate with Hassio for quite some time. Could you let me know if it's possible to implement a "bang-bang controller" (also known as a hysteresis, two-step, or on-off controller) with this thermostat?

I currently have a heater element controlled by a relay switch that manages a boiler. At the moment, I'm using an Esphome Bang-Bang controller, but I would prefer to switch to a Hassio thermostat that offers the same functionality.

I recently discovered this thermostat and am curious to know if it already supports this feature, or if it's possible for you to implement this type of controller.

![image](https://github.com/user-attachments/assets/e61d42e0-28d6-42bf-b342-c838305bbd60)

**Example Esphome Bang Bang

```
climate:
  - platform: bang_bang
    name: "Bang Bang Climate Controller"
    sensor: my_temperature_sensor
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C

    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
```

I just like the template option for the cold and hot tolerance because the generic does not allow.
so I do it now like this.

```
climate:
  - platform: universal_thermostat
    name: "Thermostat 01"
    unique_id: universal_thermostat_01
    target_sensor: sensor.virtual_temperature_bangbang
    heater: 
      - entity_id: switch.virtual_vw_element_01
        inverted: false
        keep_alive: 5
        cold_tolerance: "{{ states('input_number.cold_tolerance') | float }}"  
        hot_tolerance: "{{ states('input_number.hot_tolerance') | float }}"  
    min_temp: 40
    max_temp: 60
    target_temp: 50  
    initial_hvac_mode: "heat"
    precision: 0.1
```

It would be great if you can make this into a bang bang, so the UI wil be seen as the esphome example
thank you for your time.

Greetings from Hollanda

**Comment by vaproloff** [comment]
Hi, @mupsje !

I didn't quite understand what the task was;) I'm sorry)
If you have toggleable switch and temperature sensor entity, you can use my component (as well as more simple standard HA [generic_thermostat](https://www.home-assistant.io/integrations/generic_thermostat/)).

If you prefer using my component, here is an config example:

```
climate:
  - platform: universal_thermostat    
    name: My Thermostat
    target_sensor: sensor.my_temperature_sensor  # your sensor entity
    min_temp: 18
    max_temp: 28
    precision: 0.1    
    target_temp_step: 0.5
    heater:
      - entity_id: switch.my_heater  # your switch entity
        cold_tolerance: 0.3
        hot_tolerance: 0.3
```

You can also use it with PWM mode, but I would not recommend it if you have electromagnetic relay (it won't last long). Use it only if you have solid state relay.

```
climate:
  - platform: universal_thermostat    
    name: My Thermostat
    target_sensor: sensor.my_temperature_sensor  # your sensor entity
    min_temp: 18
    max_temp: 28
    precision: 0.1    
    target_temp_step: 0.5
    heater:
      - entity_id: switch.my_heater  # your switch entity
        cold_tolerance: 0.3
        hot_tolerance: 0.3
        kp: 20
        ki: 0.001
        kd: 10000
        pwm_period: 300
```

I hope I understood your question correctly;)

**Comment by mupsje** [comment]
Thank you for your response! I appreciate your insights.

Indeed, language barriers can sometimes lead to misunderstandings, but no worries.

I wanted to share my setup for a `climate.bangbang` controller:

## Equipment:
- `switch.heaterelement`
- `sensor.supply_boiler_temp`

## Setpoints:
- Temperature low: 50°C -> Switch on
- Temperature high: 55°C -> Switch off

There's no target temperature. With your "thermostat," we can use a "template" to dynamically adjust the hot and cold tolerance settings, which isn't possible with the "generic" option from Home Assistant. Thank you for enabling this functionality!

This setup is what we call a bang-bang or dynamic hysteresis climate controller. As shown in the previous image (esphome climate), you'll notice two white dots representing the setpoints at 50°C and 55°C.

I'm currently using your solution, and it works perfectly! Thank you once again.

## Input numbers to control the setpoints hysteresis:
```yaml:configuration.yaml
input_number:
  hot_tolerance_01:
    name: Hot Tolerance Element 01
    initial: 3
    min: 0.1
    max: 5.0
    step: 0.1
    mode: box

  cold_tolerance_01:
    name: Cold Tolerance Element 01
    initial: 3
    min: 0.1
    max: 5.0
    step: 0.1
    mode: box
 ```

## Sensors for Dynamic Control:

```yaml:configuration.yaml
sensor:
  - platform: template
    sensors:
      dynamic_hot_tolerance_01:
        unique_id: dynamic_hot_tolerance_01
        value_template: "{{ states('input_number.hot_tolerance_01') | float }}"

      dynamic_cold_tolerance_01:
        unique_id: dynamic_cold_tolerance_01
        value_template: "{{ states('input_number.cold_tolerance_01') | float }}"
```
## Sensor for Visual UI:

```yaml:configuration.yaml
sensor:
      adjusted_temperature_hot_01:
        friendly_name: "Adjusted Temperature hot element 01"
        value_template: >
          {% set climate_temp = state_attr('climate.thermostat_01', 'temperature') | float(default=0) %}
          {% set hot_tolerance_01 = states('sensor.dynamic_hot_tolerance_01') | float(default=0) %}
          {{ climate_temp + hot_tolerance_01 }}

      adjusted_temperature_cold_01:
        friendly_name: "Adjusted Temperature cold element 01"
        value_template: >
          {% set climate_temp = state_attr('climate.thermostat_01', 'temperature') | float(default=0) %}
          {% set cold_tolerance_01 = states('sensor.dynamic_cold_tolerance_01') | float(default=0) %}
          {{ climate_temp - cold_tolerance_01 }}
```
## Climate Configuration:

```yaml:configuration.yaml
climate:
  - platform: universal_thermostat
    name: "Thermostat 01"
    unique_id: universal_thermostat_01
    target_sensor: sensor.boiler_return_temperature
    heater: 
      - entity_id: switch.virtual_vw_element_01
        inverted: false
        keep_alive: 5
        cold_tolerance: "{{ states('input_number.cold_tolerance_01') | float }}"  
        hot_tolerance: "{{ states('input_number.hot_tolerance_01') | float }}"  
    min_temp: 40
    max_temp: 60
    target_temp: 50  
    initial_hvac_mode: "heat"
    precision: 0.1
```

I'm using the `simple_thermostat` from HACS for the card layout. You can find it [here](https://github.com/nervetattoo/simple-thermostat).

![image](https://github.com/user-attachments/assets/f580adfb-f887-4a2c-9632-f56ea133223e)


I'm thrilled that this setup works. I was merely suggesting if it's possible to code the climate configuration similar to the ESPHome setup. Many might suggest using PID, but it's not feasible with this heater system.

Thank you once again for your time and assistance.

Best regards.

ps: full bangbang.yaml file [here](https://github.com/mupsje/Homeassistant/blob/main/packages/bangbang.yaml)
